#!/bin/bash

docker run -d \
  --name MinecraftServer \
  -e EULA=TRUE \
  -e TYPE=FABRIC \
  -e VERSION=1.21.11 \
  -e MODS=/data/manifest.json \
  -v `pwd`/manifest.json:/data/manifest.json:ro \
  -p 25565:25565 \
  itzg/minecraft-server
